### Create car
POST http://localhost:3000/cars
Content-Type: application/json

{
  "name": "Toyota",
  "brand": "Toyota",
  "model": "RAV 6",
  "plates": "DWR 93333",
  "officeId": 3
}

### Read cars
GET http://localhost:3000/cars

### Read car
GET http://localhost:3000/cars/9

### Update car
PATCH http://localhost:3000/cars/9
Content-Type: application/json

{
  "officeId": 3
}

### Delete car
DELETE http://localhost:3000/cars/1
