### Create car
POST http://localhost:3000/cars
Content-Type: application/json

{
  "name": "Leon",
  "brand": "Seat",
  "model": "Leon",
  "plates": "DWR 9932342"
}

### Read cars
GET http://localhost:3000/cars

### Read car
GET http://localhost:3000/cars/2

### Update car
PATCH http://localhost:3000/cars/2
Content-Type: application/json

{
  "plates": "DW 21112"
}

### Delete car
DELETE http://localhost:3000/cars/1
