### Create office
POST http://localhost:3000/offices
Content-Type: application/json

{
  "name": "Siedziba 2",
  "city": "Wrocław",
  "country": "Poland",
  "streetAddress": "Wrocławksa 22",
  "zipCode": "55-555"
}

### Read offices
GET http://localhost:3000/offices

### Read office
GET http://localhost:3000/offices/3

### Update office
PATCH http://localhost:3000/offices/2
Content-Type: application/json

{
  "zipCode": "10-255"
}

### Delete office
DELETE http://localhost:3000/offices/1